# Generated by Django 6.1 on 2026-08-18 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.CharField(db_index=True, help_text='Unique task number code (e.g., CR-TASK-001)', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Task Title / Headline', max_length=255)),
                ('description', models.TextField(help_text='Detailed task description and deliverables')),
                ('instructions', models.TextField(blank=True, help_text='Step-by-step instructions, creative briefs, specifications, or guidelines', null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / In Progress'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('deadline', models.DateTimeField(blank=True, help_text='Target completion deadline (IST)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Assign to an individual member, or leave blank for full department team visibility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, help_text='Target specific branch (e.g., Designing, Editing, Marketing) or leave blank for All Branches.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='departments.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='departments.department')),
            ],
            options={
                'verbose_name': 'Creative Task',
                'verbose_name_plural': 'Creative Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/documents/%Y/%m/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
