# Generated by Django 6.1 on 2026-08-18 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when task was marked completed', null=True),
        ),
        migrations.CreateModel(
            name='TaskExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('MORE_DAYS', 'Request More Days / Extension'), ('REASSIGN', 'Request Task Reassignment')], default='MORE_DAYS', max_length=20)),
                ('requested_days', models.PositiveIntegerField(blank=True, help_text='Number of additional days requested', null=True)),
                ('requested_deadline', models.DateTimeField(blank=True, help_text='Specific requested completion deadline', null=True)),
                ('reason', models.TextField(help_text='Reason for inability to complete within deadline / notes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Manager Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_action', models.CharField(blank=True, choices=[('EXTENDED', 'Deadline Extended'), ('REASSIGNED', 'Task Reassigned'), ('REJECTED', 'Request Rejected')], max_length=20, null=True)),
                ('manager_remarks', models.TextField(blank=True, help_text='Decision notes and feedback from Department Manager', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_extension_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_task_extensions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Task Extension Request',
                'verbose_name_plural': 'Task Extension Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(help_text='Completion remarks, delivery summary, and notes')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Task Submission',
                'verbose_name_plural': 'Task Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/submissions/%Y/%m/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.tasksubmission')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
