# Generated by Django 6.1 on 2026-08-18 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completed_at_taskextensionrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='manager_feedback',
            field=models.TextField(blank=True, help_text='Manager feedback, revision instructions, or approval notes', null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending Manager Review'), ('APPROVED', 'Approved & Marked Completed'), ('CHANGES_REQUESTED', 'Revision Requested'), ('REASSIGNED', 'Reassigned to Another Member')], db_index=True, default='PENDING', max_length=25),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_task_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when manager verified and marked task completed', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active / In Progress'), ('UNDER_REVIEW', 'Submitted / Under Review'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='remarks',
            field=models.TextField(help_text='Deliverables summary, output specs, links, and remarks'),
        ),
    ]
