# Generated by Django 6.1 on 2026-08-19 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('tasks', '0003_tasksubmission_manager_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.CharField(db_index=True, help_text='Unique client identifier code (e.g., CR-CL-001)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Client Name / Contact Person', max_length=255)),
                ('company', models.CharField(help_text='Company / Brand / Organization Name', max_length=255)),
                ('needs', models.TextField(help_text='Client creative needs, specifications, requirements, and deliverables')),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone / WhatsApp number', max_length=50, null=True)),
                ('address', models.TextField(blank=True, help_text='Company address or office location', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes or creative guidelines', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='departments.department')),
            ],
            options={
                'verbose_name': 'Creative Client',
                'verbose_name_plural': 'Creative Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Associated client for this task (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.client'),
        ),
    ]
