# Generated by Django 6.1 on 2026-08-19 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('tasks', '0004_client_task_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(help_text='Specific task title for this branch (e.g. Marketing Campaign, UI/UX Design, 4K Video Editing)', max_length=255)),
                ('task_scope', models.TextField(help_text='Specific instructions, deliverables, and scope delegated to this branch')),
                ('deadline', models.DateTimeField(blank=True, help_text='Target completion deadline', null=True)),
                ('status', models.CharField(choices=[('ASSIGNED_TO_EXECUTIVE', 'Assigned to Branch Executive'), ('DELEGATED', 'Delegated to Member / Intern'), ('IN_PROGRESS', 'In Progress'), ('UNDER_REVIEW', 'Completed / Under Review'), ('COMPLETED', 'Completed'), ('ON_HOLD', 'On Hold')], db_index=True, default='ASSIGNED_TO_EXECUTIVE', max_length=30)),
                ('delegated_at', models.DateTimeField(blank=True, null=True)),
                ('executive_notes', models.TextField(blank=True, help_text='Guidance, instructions, or allocation remarks from the Branch Executive', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(help_text='Creative Department Manager who initiated the branch assignment', on_delete=django.db.models.deletion.CASCADE, related_name='manager_client_assignments', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to='departments.branch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.client')),
                ('delegated_member', models.ForeignKey(blank=True, help_text='Staff member or intern assigned by the Branch Executive', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_assigned_client_tasks', to=settings.AUTH_USER_MODEL)),
                ('executive', models.ForeignKey(help_text='Branch Executive responsible for supervising and delegating', on_delete=django.db.models.deletion.CASCADE, related_name='executive_received_client_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Branch Assignment',
                'verbose_name_plural': 'Client Branch Assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
