# Generated by Django 6.1 on 2026-08-19 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_clientassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientassignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED_TO_EXECUTIVE', 'Assigned to Branch Executive'), ('DELEGATED', 'Delegated to Member / Intern'), ('IN_PROGRESS', 'In Progress'), ('UNDER_EXECUTIVE_REVIEW', 'Submitted / Under Executive Review'), ('EXECUTIVE_REVISION', 'Revision Requested by Executive'), ('UNDER_DEPT_MANAGER_REVIEW', 'Forwarded to Dept Manager / Final Review'), ('DEPT_MANAGER_REVISION', 'Revision Requested by Dept Manager'), ('COMPLETED', 'Approved & Completed'), ('ON_HOLD', 'On Hold'), ('UNDER_REVIEW', 'Completed / Under Review')], db_index=True, default='ASSIGNED_TO_EXECUTIVE', max_length=35),
        ),
        migrations.CreateModel(
            name='ClientAssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(help_text='Deliverables summary, output specs, links, and remarks')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('review_stage', models.CharField(choices=[('PENDING_EXECUTIVE', 'Pending Executive Review'), ('EXECUTIVE_REVISION_REQUESTED', 'Revision Requested by Executive'), ('FORWARDED_TO_MANAGER', 'Forwarded to Dept Manager'), ('MANAGER_REVISION_REQUESTED', 'Revision Requested by Dept Manager'), ('MANAGER_APPROVED', 'Approved by Dept Manager')], db_index=True, default='PENDING_EXECUTIVE', max_length=35)),
                ('executive_feedback', models.TextField(blank=True, help_text='Executive review feedback or revision instructions', null=True)),
                ('executive_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_feedback', models.TextField(blank=True, help_text='Department Manager final evaluation remarks', null=True)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.clientassignment')),
                ('executive_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exec_reviewed_client_submissions', to=settings.AUTH_USER_MODEL)),
                ('manager_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mgr_reviewed_client_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Assignment Submission',
                'verbose_name_plural': 'Client Assignment Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientAssignmentSubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/client_submissions/%Y/%m/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.clientassignmentsubmission')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
