# Generated by Django 6.1 on 2026-08-19 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Candidate Name')),
                ('phone', models.CharField(max_length=25, verbose_name='Contact Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('place', models.CharField(max_length=150, verbose_name='Place / City / Location')),
                ('role_applied', models.CharField(choices=[('STAFF', 'Staff Member'), ('EXECUTIVE', 'Branch Executive'), ('INTERN', 'Department Intern'), ('MANAGER', 'Manager'), ('DEPT_MANAGER', 'Department Manager'), ('OTHER', 'Other Specialist')], default='STAFF', max_length=30, verbose_name='Role / Level Applied')),
                ('designation_applied', models.CharField(blank=True, default='', help_text='e.g. Senior Graphic Designer, Video Editor, Marketing Associate', max_length=150, verbose_name='Designation / Position Title')),
                ('qualification', models.CharField(blank=True, default='', max_length=150, verbose_name='Highest Educational Qualification')),
                ('experience_years', models.CharField(blank=True, default='', help_text='e.g. Fresher, 2 Years, 5+ Years', max_length=50, verbose_name='Relevant Experience')),
                ('resume', models.FileField(blank=True, null=True, upload_to='candidate_resumes/', verbose_name='Resume / CV / Portfolio Attachment')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Initial Candidate Notes / Summary')),
                ('status', models.CharField(choices=[('TO_BE_CALLED', 'To Be Called'), ('CALLED', 'Called'), ('APPROVED', 'Approved After Calling'), ('REJECTED', 'Rejected'), ('INTERVIEW_SCHEDULED', 'Interview Arranged'), ('INTERVIEWED', 'Interview Completed'), ('SELECTED', 'Selected'), ('ONBOARDED', 'Onboarded as Employee')], db_index=True, default='TO_BE_CALLED', max_length=30, verbose_name='Candidate Pipeline Status')),
                ('called_at', models.DateTimeField(blank=True, null=True, verbose_name='Call Completed At')),
                ('call_notes', models.TextField(blank=True, default='', verbose_name='Calling Summary & Discussion Notes')),
                ('call_rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 - Needs Improvement'), (2, '2 - Fair'), (3, '3 - Good / Promising'), (4, '4 - Very Good'), (5, '5 - Exceptional Candidate')], null=True, verbose_name='Phone Screening Rating')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Decision Date')),
                ('approval_notes', models.TextField(blank=True, default='', verbose_name='Approval / Shortlist Remarks')),
                ('interview_date', models.DateField(blank=True, null=True, verbose_name='Interview Date')),
                ('interview_time', models.TimeField(blank=True, null=True, verbose_name='Interview Time')),
                ('interview_mode', models.CharField(choices=[('IN_PERSON', 'In-Person (Office)'), ('ONLINE', 'Online (Google Meet / Zoom)'), ('PHONE', 'Telephonic Interview')], default='IN_PERSON', max_length=20, verbose_name='Interview Format')),
                ('interview_location', models.CharField(blank=True, default='', help_text='e.g. HQ Office Room 302, or Google Meet URL', max_length=255, verbose_name='Interview Location / Meeting Link')),
                ('interviewer_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Interviewer(s) / Panel')),
                ('interview_instructions', models.TextField(blank=True, default='', verbose_name='Instructions for Candidate')),
                ('interview_feedback', models.TextField(blank=True, default='', verbose_name='Post-Interview Evaluation Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='departments.branch', verbose_name='Applied Branch Wing')),
                ('called_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='called_candidates', to=settings.AUTH_USER_MODEL, verbose_name='HR Executive who Called')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_candidates', to=settings.AUTH_USER_MODEL, verbose_name='Registered By')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='departments.department', verbose_name='Applied Department')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_candidates', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed & Decided By')),
            ],
            options={
                'verbose_name': 'Candidate Application',
                'verbose_name_plural': 'Candidate Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
