# Generated by Django 6.1 on 2026-08-18 04:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick / Medical Leave'), ('ANNUAL', 'Annual / Earned Leave'), ('UNPAID', 'Unpaid Leave (LWP)'), ('EMERGENCY', 'Emergency Leave')], default='CASUAL', max_length=25)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_half_day', models.BooleanField(default=False)),
                ('half_day_period', models.CharField(blank=True, choices=[('FIRST_HALF', 'First Half (Morning)'), ('SECOND_HALF', 'Second Half (Afternoon)')], max_length=15, null=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING_DEPT_REVIEW', 'Pending Dept Manager Review'), ('PENDING_MANAGER_APPROVAL', 'Pending Manager Final Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by Applicant')], db_index=True, default='PENDING_DEPT_REVIEW', max_length=30)),
                ('dept_manager_notes', models.TextField(blank=True, default='')),
                ('dept_manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_decision_notes', models.TextField(blank=True, default='')),
                ('manager_decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by_dept_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_reviewed_leaves', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Application',
                'verbose_name_plural': 'Leave Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'On Leave')], db_index=True, default='ABSENT', max_length=20)),
                ('work_duration_minutes', models.PositiveIntegerField(default=0)),
                ('check_in_notes', models.TextField(blank=True, null=True)),
                ('check_out_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Attendance Record',
                'verbose_name_plural': 'Daily Attendance Records',
                'ordering': ['-date', 'user'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
