# Generated by Django 6.1 on 2026-08-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_late',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Present (Late)'), ('HALF_DAY', 'Half Day'), ('ABSENT', 'Absent'), ('ON_LEAVE', 'On Leave')], db_index=True, default='ABSENT', max_length=20),
        ),
    ]
