# Generated by Django 6.1 on 2026-08-19 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_is_late_alter_attendance_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by_superadmin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superadmin_approved_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='superadmin_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='superadmin_decision_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING_DEPT_REVIEW', 'Pending Dept Manager Review'), ('PENDING_MANAGER_APPROVAL', 'Pending Manager Final Approval'), ('PENDING_SUPERADMIN_APPROVAL', 'Pending Super Admin Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by Applicant')], db_index=True, default='PENDING_DEPT_REVIEW', max_length=30),
        ),
    ]
